sudo: required
language: minimal
before_install:
  - pwd
  - cd
  - wget http://chymera.eu/distfiles/stemgentoo/2019-11-23.tar.xz
  - mkdir -p gentoo
  - tar -xf 2019-11-23.tar.xz --exclude='dev/*' -C gentoo &> gentoo_extraction.log
  - cp -L /etc/resolv.conf gentoo/etc/
  - sudo mount --bind /dev gentoo/dev
  - sudo mount --bind /sys gentoo/sys
  - sudo mount --bind /proc gentoo/proc
  - sudo chroot gentoo/ /bin/bash -c "emerge --quiet --sync"
  - sudo env -i PATH="$PATH" chroot gentoo/ /bin/bash -c "emerge -1q portage"
install:
  - mv build/IBT-FMI/gebuilder gentoo/gebuilder
  - find gentoo/gebuilder/
  - ls -lah
  - pwd
  - ls gentoo -lah
  - sudo env -i PATH="$PATH" chroot gentoo/ /bin/bash -c "/gebuilder/.gentoo/install.sh --autounmask-continue=y --autounmask=y"
script:
  - sudo env -i PATH="$PATH" chroot gentoo/ /bin/bash -c "FEATUERS=\"test\" /gebuilder/.gentoo/install.sh --autounmask-continue=y --autounmask=y"

#language: python
#before_install:
#  - docker pull gebuilder/gebuilder_environment
#  - docker create --name "gebuilder_environment" --rm -ti -v "${PWD}":/home/gebuilder_environment gebuilder/gebuilder_environment
#  - docker start gebuilder_environment
#  # Re-emerging dependencies in not needed if the environment image is regenerated frequently (e.g. weekly)
#  #- docker exec gebuilder_environment emaint sync -a
#  #- docker exec gebuilder sh -c '/home/gebuilder/.gentoo/install.sh -o --autounmask-continue'
#install:
#  # Re/Install the package without tests, this is not separately needed as it is included in the script below:
#  #- docker exec gebilder_environment sh -c 'FEATURES="-test" /home/gebuilder_environment/.gentoo/install.sh --autounmask-continue'
#script:
#  # Install and run tests (this is performed separately from dependency installation so as to not propagate the test FEATURE to the entire graph):
#  - docker exec gebuilder_environment sh -c 'FEATURES="test" /home/gebuilder_environment/.gentoo/install.sh --autounmask-continue'
