.TH GEBUILD 8
.SH NAME
gebuild \- generates software environments based on an ebuild specification
.SH SYNOPSIS
.B gebuild
[/path/to/.gentoo|stemgentoo]
[\fIcommand\fR]
.SH DESCRIPTION
.B gebuild
is a Gentoo system and image builder which can produce system tarballs, OpenStack Images, and Docker containers based on the .gentoo live package distribution standard.

.SH SEE ALSO
A more extensive description of the background for this project and the .gentoo specification is laid out in the summary of the semester project during which this project was initially launched (http://chymera.eu/docs/dominik_semesterarbeit.pdf).
